export const POST_OAUTH_TOKEN_REQUEST = 'POST_OAUTH_TOKEN_REQUEST';
export const POST_OAUTH_TOKEN_SUCCESS = 'POST_OAUTH_TOKEN_SUCCESS';
export const POST_OAUTH_TOKEN_FAILURE = 'POST_OAUTH_TOKEN_FAILURE';

export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'


export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';

export const POST_TOUR_SUCCESS = 'POST_TOUR_SUCCESS';
export const POST_TOUR_FAILURE = 'POST_TOUR_FAILURE';

export const NEXT_STEP = 'NEXT_STEP'
export const PREV_STEP = 'PREV_STEP'


export const PRESERV_ANSWER = 'PRESERV_ANSWER';