export const POST_OAUTH_TOKEN_REQUEST = 'POST_OAUTH_TOKEN_REQUEST';
export const POST_OAUTH_TOKEN_SUCCESS = 'POST_OAUTH_TOKEN_SUCCESS';
export const POST_OAUTH_TOKEN_FAILURE = 'POST_OAUTH_TOKEN_FAILURE';


export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
